### ISSUE TITLE
Inconsistent white space in `Invoke-Action`

### ISSUE THREAD

**Issue by benmusson** [benmusson/ahk2exe-action#7]
Not sure why, but in the online GH code viewer the whitespace in Invoke-Action is messed up.

https://github.com/benmusson/ahk2exe-action/blob/1f0f0fe92da8fafcc9cacd882bda8cfbad075e02/action.ps1#L223

**Comment by SaifAqqad** [comment]
It's caused by mixing spaces and tabs (the dots are spaces and the arrows are tabs)

![image](https://github.com/user-attachments/assets/64ec90e6-840e-4341-aeae-8da393959764)
